{
 "title": "HTTP servers monitoring",
 "tags": [
  "go",
  "http"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "endpoint",
    "query": {
     "query": "label_values(http_request_duration_seconds_bucket,handler)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "HTTP RPS",
   "type": "timeseries",
   "description": "Requests per second for $service (regardless of error).",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(http_request_duration_seconds_count{handler=~\"$endpoint\"}[$__rate_interval]))",
     "legendFormat": "total"
    },
    {
     "expr": "sum by(handler) (rate(http_request_duration_seconds_count{handler=~\"$endpoint\"}[$__rate_interval])) > 0",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "HTTP codes response overview",
   "type": "timeseries",
   "description": "Number of requests that returned given code",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(handler, method, code) (rate(http_request_duration_seconds_count{handler=~\"$endpoint\"}[$__rate_interval])) > 0",
     "legendFormat": "{{method}} {{code}} {{handler}}"
    }
   ]
  },
  {
   "title": "HTTP handle time 0.95 percentile",
   "type": "timeseries",
   "description": "How much time took 0.95 part of all requests to the endpoint.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "repeat": "percentile",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(handler, code, le) (rate(http_request_duration_seconds_bucket{handler=~\"$endpoint\"}[$__rate_interval])))",
     "legendFormat": "{{handler}} {{code}}"
    }
   ]
  },
  {
   "title": "HTTP time interval",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum by(le) (increase(http_request_duration_seconds_bucket{le=\"0.0005\", handler=~\"$endpoint\"}[1m]))",
     "legendFormat": "<0.5 ms"
    },
    {
     "expr": "sum by(le) (increase(http_request_duration_seconds_bucket{le=\"0.001\", handler=~\"$endpoint\"}[1m])) - ignoring(le) sum by(le) (increase(http_request_duration_seconds_bucket{le=\"0.0005\", handler=~\"$endpoint\"}[1m]))",
     "legendFormat": "0.5-1 ms"
    },
    {
     "expr": "sum by(le) (increase(http_request_duration_seconds_bucket{le=\"0.005\", handler=~\"$endpoint\"}[1m])) - ignoring(le) sum by(le) (increase(http_request_duration_seconds_bucket{le=\"0.001\", handler=~\"$endpoint\"}[1m]))",
     "legendFormat": "1-5 ms"
    },
    {
     "expr": "sum by(le) (increase(http_request_duration_seconds_bucket{le=\"0.01\", handler=~\"$endpoint\"}[1m])) - ignoring(le) sum by(le) (increase(http_request_duration_seconds_bucket{le=\"0.005\", handler=~\"$endpoint\"}[1m]))",
     "legendFormat": "5-10 ms"
    },
    {
     "expr": "sum by(le) (increase(http_request_duration_seconds_bucket{le=\"0.015\", handler=~\"$endpoint\"}[1m])) - ignoring(le) sum by(le) (increase(http_request_duration_seconds_bucket{le=\"0.01\", handler=~\"$endpoint\"}[1m]))",
     "legendFormat": "10-15ms"
    },
    {
     "expr": "sum by(le) (increase(http_request_duration_seconds_bucket{le=\"0.02\", handler=~\"$endpoint\"}[1m])) - ignoring(le) sum by(le) (increase(http_request_duration_seconds_bucket{le=\"0.015\", handler=~\"$endpoint\"}[1m]))",
     "legendFormat": "15-20ms"
    },
    {
     "expr": "sum by(le) (increase(http_request_duration_seconds_bucket{le=\"0.025\", handler=~\"$endpoint\"}[1m])) - ignoring(le) sum by(le) (increase(http_request_duration_seconds_bucket{le=\"0.02\", handler=~\"$endpoint\"}[1m]))",
     "legendFormat": "20-25 ms"
    },
    {
     "expr": "sum by(le) (increase(http_request_duration_seconds_bucket{le=\"+Inf\", handler=~\"$endpoint\"}[1m])) - ignoring(le) sum by(le) (increase(http_request_duration_seconds_bucket{le=\"0.025\", handler=~\"$endpoint\"}[1m]))",
     "legendFormat": ">25ms"
    }
   ]
  }
 ]
}